version: '3.8'

services:
  nginx:
    depends_on:
      - api
      - app
    restart: always
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 3050:80

  api:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3001 -w db.json
    volumes:
      - ./db.json:/data/db.json
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /usr/app/node_modules
      - ./src:/usr/app/src